echo "Comparation:"
echo "========================"
echo "alembic_version"
sqlite3 mpeds.db "select count(*) from alembic_version"
mysql -uroot -Dmpeds -e"select count(*) from alembic_version;"
echo "------------------------"
echo "article_metadata"
sqlite3 mpeds.db "select count(*) from article_metadata"
mysql -uroot -Dmpeds -e"select count(*) from article_metadata;"
echo "------------------------"
echo "article_queue"
sqlite3 mpeds.db "select count(*) from article_queue"
mysql -uroot -Dmpeds -e"select count(*) from article_queue;"
echo "------------------------"
echo "code_first_pass"
sqlite3 mpeds.db "select count(*) from code_first_pass"
mysql -uroot -Dmpeds -e"select count(*) from code_first_pass;"
echo "------------------------"
echo "coder_second_pass"
sqlite3 mpeds.db "select count(*) from coder_second_pass"
mysql -uroot -Dmpeds -e"select count(*) from coder_second_pass;"
echo "------------------------"
echo "event"
sqlite3 mpeds.db "select count(*) from event"
mysql -uroot -Dmpeds -e"select count(*) from event;"
echo "------------------------"
echo "second_pass_queue"
sqlite3 mpeds.db "select count(*) from second_pass_queue"
mysql -uroot -Dmpeds -e"select count(*) from second_pass_queue;"
echo "------------------------"
echo "user"
sqlite3 mpeds.db "select count(*) from user"
mysql -uroot -Dmpeds -e"select count(*) from user;"
echo "------------------------"
echo "var_option"
sqlite3 mpeds.db "select count(*) from var_option"
mysql -uroot -Dmpeds -e"select count(*) from var_option;"
echo "========================"
